project_id = "kbfbbkcaxhzlnbqxwgoz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.provision-tenant]
verify_jwt = false

[functions.invite-employee]
verify_jwt = true